/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.security.NoSuchAlgorithmException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager.*;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import logica.db.Usuario;

/**
 *
 * @author CTesting
 */
public class loguin extends javax.swing.JFrame {

    //mesero m = new mesero();
    cajero caje = new cajero();
    private int c = 0;
    Calendar calendar = new GregorianCalendar();

    /**
     * Creates new form loguin
     */
    public loguin() {
        initComponents();
        JLabel fondo = new JLabel();
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/6587891465_9800849c79.jpg")));
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, fondo.getIcon().getIconWidth(), fondo.getIcon().getIconHeight());
        this.setSize(470, 350);
        panel.setOpaque(true);
        panel.setBackground(new Color(255, 255, 255, 60));
        this.setLocationRelativeTo(null);
        //Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ima/logo-1.png"));
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ima/barra/logo2.png"));
        setIconImage(icon);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        passClave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Session de Usuarios");
        setResizable(false);
        getContentPane().setLayout(null);

        txtUsuario.setSelectedTextColor(new java.awt.Color(243, 116, 7));
        txtUsuario.setSelectionColor(new java.awt.Color(236, 88, 16));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/1437653614_account_friend_human_man_member_person_profile_user_users.png"))); // NOI18N
        jLabel1.setText("Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/1437653992_Hide_password.png"))); // NOI18N
        jLabel2.setText("Clave");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/1437653441_Login_in.png"))); // NOI18N
        jButton1.setText("Iniciar sesión");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passClave, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(panel);
        panel.setBounds(60, 79, 340, 180);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/7879247420_7e13562e7c_c-640x425.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 470, 350);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 0, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (c >= 3) {
            this.dispose();
        }
        if (!txtUsuario.getText().equalsIgnoreCase("")) {
            String c1 = String.valueOf(passClave.getPassword());
            if (c1.length() > 0) {
                try {
                    inventario.logica.db.Empleado empleado = new inventario.logica.db.Empleado();
                    System.out.println(empleado.validarPass(txtUsuario.getText(), c1));
                    inventario.logica.Empleado emple = (inventario.logica.Empleado)empleado.getDato(new String[]{txtUsuario.getText(), c1});
                    if (empleado.validarPass(txtUsuario.getText(), c1)) {
                        cajero caje = new cajero(emple.getNegocio());
                        caje.setTemporal_empleado(emple);
                        caje.cargarInformacion();
                        caje.setLocale(null);
                        caje.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Usurio i/o contraseña incorrecto.");
                    }
                }catch (NoSuchAlgorithmException ex) {
                    JOptionPane.showMessageDialog(null, "Reinicie el cliente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe digitar la clave para el usuario");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tiene que digitar el usuario.");
        }
//            if (c >= 3) {
//                this.dispose();
//            }
//            if (!txtUsuario.getText().equalsIgnoreCase("")) {
//                String c1 = String.valueOf(passClave.getPassword());
//                if (c1.length() > 0) {
//                    Usuario u = new Usuario();
//                    try {
//                        if (u.validarPass(new logica.Usuario(txtUsuario.getText(), c1))) {
//                            Object o = u.getDato(new logica.Usuario(txtUsuario.getText(), c1));
//                            if (o != null) {
//                                logica.Usuario us = (logica.Usuario) o;
//                                this.setVisible(false);
//                                if (us.getTipo() == 1) {
//
//                                    admin a = new admin();
//                                    a.setLocale(null);
//                                    a.setVisible(true);
//                                } else {
//                                    m.repaint();
//                                    m.setLocale(null);
//                                    m.setVisible(true);
//                                }
//                            } else {
//                                JOptionPane.showMessageDialog(null, "El usuario y/o clave no coinciden .");
//                                c++;
//                            }
//                        } else {
//                            JOptionPane.showMessageDialog(null, "El usuario y/o clave no coinciden.");
//                            c++;
//                        }
//                    } catch (NoSuchAlgorithmException ex) {
//                        JOptionPane.showMessageDialog(null, "Debe digitar la clave para el usuario correctamente");
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(null, "Debe digitar la clave para el usuario");
//                }
//            } else {
//                JOptionPane.showMessageDialog(null, "Tiene que digitar el usuario.");
//            }

    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void paint(Graphics g) {
        ImageIcon ima = new javax.swing.ImageIcon(getClass().getResource("/ima/6587891465_9800849c79.jpg"));
        g.drawImage(ima.getImage(), 0, 0, this.getWidth(), this.getHeight(), this);
        super.paintComponents(g);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
                } catch (Exception rt) {
                }
                new loguin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField passClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
